apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: strigus
  name: deploy-strigus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strigus
  template:
    metadata:
      labels:
        app: strigus
    spec:
      containers:
      - image: nginx
        name: strigus
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.3"
            memory: "64Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always      
---
apiVersion: v1
kind: Service
metadata:
  name: service-strigus
spec:
  selector:
    app: strigus
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer            
